export var constants = {
    
    GET_PRODUCTS_BY_DEALER :'GET_PRODUCTS_BY_DEALER',
    GET_PRODUCT_BY_ID :'GET_PRODUCT_BY_ID',    
    GET_DEALER_BY_NUMBER :'GET_DEALER_BY_NUMBER',    
    BAD_REQUEST: 400,
    ERROR_504: 504,
    SERVICE_UNAVAILABLE: 0

};